#!/bin/bash
CURL=`which curl`
if [ ! -z "$CURL" ]; then
	if [ ! -z "$1" ]; then
		if $CURL --head --location --silent --fail "$1" > /dev/null
		then
    			echo "true"
		else
    			echo "false"
		fi 
	
	else
		echo "false"
	fi
else
	echo "error, curl does not exist!!"
	exit 1
fi

